import { UserRole } from '../types';

export interface ReportFilterOptions {
  instituteName?: string;
  departmentName?: string;
  programName?: string;
  academicYearName?: string;
  semesterName?: string;
  divisionName?: string;
  startDate?: string;
  endDate?: string;
  searchQuery?: string;
}

export interface UserExportMetadata {
  name?: string;
  role?: UserRole;
  designation?: string;
  email?: string;
}

/**
 * Format date for reports (e.g. 12 August 2026, 01:45 PM)
 */
const formatReportTimestamp = (): string => {
  const now = new Date();
  return now.toLocaleString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  });
};

/**
 * Export dataset to Excel (.xlsx compatible CSV with UTF-8 BOM)
 */
export const exportToExcel = (
  reportTitle: string,
  headers: string[],
  rows: (string | number)[][],
  filters: ReportFilterOptions,
  userMeta?: UserExportMetadata
) => {
  const timestamp = formatReportTimestamp();
  
  // Format filter summary string
  const activeFilters = [
    filters.instituteName && filters.instituteName !== 'ALL' ? `Institute: ${filters.instituteName}` : null,
    filters.departmentName && filters.departmentName !== 'ALL' ? `Department: ${filters.departmentName}` : null,
    filters.programName && filters.programName !== 'ALL' ? `Program: ${filters.programName}` : null,
    filters.academicYearName && filters.academicYearName !== 'ALL' ? `Academic Year: ${filters.academicYearName}` : null,
    filters.semesterName && filters.semesterName !== 'ALL' ? `Semester: ${filters.semesterName}` : null,
    filters.divisionName && filters.divisionName !== 'ALL' ? `Division: ${filters.divisionName}` : null,
    filters.startDate ? `From: ${filters.startDate}` : null,
    filters.endDate ? `To: ${filters.endDate}` : null,
    filters.searchQuery ? `Search: "${filters.searchQuery}"` : null
  ].filter(Boolean).join(' | ') || 'All Records (Unfiltered)';

  // Build CSV content with metadata headers
  const csvLines: string[] = [
    `"SWARRNIM STARTUP & INNOVATION UNIVERSITY"`,
    `"OFFICIAL NAAC / UGC COMPLIANT ERP DATA REPORT"`,
    `"Report Title: ${reportTitle}"`,
    `"Generated On: ${timestamp}"`,
    `"Generated By: ${userMeta?.name || 'Authorized ERP User'} (${userMeta?.role || 'ERP User'})"`,
    `"Applied Filters: ${activeFilters}"`,
    `"Total Records: ${rows.length}"`,
    `""`, // Blank line separator
    headers.map(h => `"${h.replace(/"/g, '""')}"`).join(','),
    ...rows.map(row => 
      row.map(cell => {
        const strVal = cell === null || cell === undefined ? '' : String(cell);
        return `"${strVal.replace(/"/g, '""')}"`;
      }).join(',')
    )
  ];

  const csvString = '\uFEFF' + csvLines.join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  const sanitizedTitle = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  link.setAttribute('href', url);
  link.setAttribute('download', `ssiu_report_${sanitizedTitle}_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Export dataset to Word Document (.doc with University Letterhead Styling)
 */
export const exportToWord = (
  reportTitle: string,
  headers: string[],
  rows: (string | number)[][],
  filters: ReportFilterOptions,
  userMeta?: UserExportMetadata
) => {
  const timestamp = formatReportTimestamp();
  
  const activeFilters = [
    filters.instituteName && filters.instituteName !== 'ALL' ? `Institute: ${filters.instituteName}` : null,
    filters.departmentName && filters.departmentName !== 'ALL' ? `Department: ${filters.departmentName}` : null,
    filters.programName && filters.programName !== 'ALL' ? `Program: ${filters.programName}` : null,
    filters.academicYearName && filters.academicYearName !== 'ALL' ? `Academic Year: ${filters.academicYearName}` : null,
    filters.semesterName && filters.semesterName !== 'ALL' ? `Semester: ${filters.semesterName}` : null,
    filters.divisionName && filters.divisionName !== 'ALL' ? `Division: ${filters.divisionName}` : null,
    filters.startDate ? `From: ${filters.startDate}` : null,
    filters.endDate ? `To: ${filters.endDate}` : null,
    filters.searchQuery ? `Search: "${filters.searchQuery}"` : null
  ].filter(Boolean).join(' | ') || 'All Records (Unfiltered)';

  const tableHeaderHtml = headers.map(h => 
    `<th style="background-color: #0F2C59; color: #FFFFFF; font-weight: bold; padding: 10px 8px; border: 1px solid #1E3E62; text-align: left; font-size: 11px; text-transform: uppercase;">${h}</th>`
  ).join('');

  const tableRowsHtml = rows.map((row, idx) => {
    const bg = idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
    const cellsHtml = row.map(cell => 
      `<td style="padding: 8px; border: 1px solid #CBD5E1; font-size: 11px; color: #1E293B;">${cell === null || cell === undefined ? '' : String(cell)}</td>`
    ).join('');
    return `<tr style="background-color: ${bg};">${cellsHtml}</tr>`;
  }).join('');

  const htmlDocument = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <title>${reportTitle} - Swarrnim University</title>
      <style>
        @page {
          size: A4 portrait;
          margin: 20mm 15mm 20mm 15mm;
          @bottom-right {
            content: "Page " counter(page) " of " counter(pages);
            font-size: 9pt;
            font-family: Arial, sans-serif;
            color: #64748B;
          }
        }
        body {
          font-family: 'Segoe UI', Arial, sans-serif;
          color: #0F172A;
          line-height: 1.4;
          margin: 0;
          padding: 0;
        }
        .univ-header {
          text-align: center;
          border-bottom: 3px double #0F2C59;
          padding-bottom: 12px;
          margin-bottom: 16px;
        }
        .univ-name {
          font-size: 18pt;
          font-weight: 800;
          color: #0F2C59;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin: 0;
        }
        .univ-subtitle {
          font-size: 9pt;
          color: #F37023;
          font-weight: 700;
          text-transform: uppercase;
          letter-spacing: 1px;
          margin-top: 4px;
        }
        .univ-address {
          font-size: 8.5pt;
          color: #475569;
          margin-top: 2px;
        }
        .report-badge-bar {
          background-color: #F1F5F9;
          border-left: 4px solid #F37023;
          padding: 10px 14px;
          margin-bottom: 16px;
          border-radius: 4px;
        }
        .report-title {
          font-size: 14pt;
          font-weight: 800;
          color: #0F2C59;
          margin: 0 0 6px 0;
        }
        .meta-grid {
          font-size: 9pt;
          color: #334155;
        }
        .meta-item {
          margin-bottom: 3px;
        }
        .data-table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 16px;
          margin-bottom: 24px;
        }
        .signature-block {
          margin-top: 40px;
          page-break-inside: avoid;
        }
        .sig-table {
          width: 100%;
          border: none;
        }
        .sig-cell {
          width: 33%;
          text-align: center;
          vertical-align: bottom;
          padding-top: 45px;
          font-size: 9.5pt;
          color: #0F2C59;
        }
        .sig-line {
          border-top: 1.5px solid #0F2C59;
          width: 80%;
          margin: 0 auto 6px auto;
        }
        .footer-note {
          font-size: 8pt;
          color: #94A3B8;
          text-align: center;
          margin-top: 24px;
          border-top: 1px solid #E2E8F0;
          padding-top: 8px;
        }
      </style>
    </head>
    <body>
      <div class="univ-header">
        <div class="univ-name">Swarrnim Startup &amp; Innovation University</div>
        <div class="univ-subtitle">NAAC Grade A+ Accredited • Government Recognized Statutory University</div>
        <div class="univ-address">Bhoyan Rathod, Opposite IFFCO Township, Gandhinagar-Ahmedabad Highway, Gujarat 382421</div>
      </div>

      <div class="report-badge-bar">
        <div class="report-title">${reportTitle}</div>
        <div class="meta-grid">
          <div class="meta-item"><strong>Generated On:</strong> ${timestamp}</div>
          <div class="meta-item"><strong>Generated By:</strong> ${userMeta?.name || 'Authorized ERP User'} (${userMeta?.designation || userMeta?.role || 'ERP Administrative Office'})</div>
          <div class="meta-item"><strong>Applied Scope / Filters:</strong> ${activeFilters}</div>
          <div class="meta-item"><strong>Total Records Exported:</strong> ${rows.length} Records</div>
        </div>
      </div>

      <table class="data-table">
        <thead>
          <tr>${tableHeaderHtml}</tr>
        </thead>
        <tbody>
          ${tableRowsHtml}
        </tbody>
      </table>

      <div class="signature-block">
        <table class="sig-table">
          <tr>
            <td class="sig-cell">
              <div class="sig-line"></div>
              <strong>Prepared By</strong><br/>
              <span style="font-size: 8.5pt; color: #64748B;">System Officer / ERP Custodian</span>
            </td>
            <td class="sig-cell">
              <div class="sig-line"></div>
              <strong>Verified By</strong><br/>
              <span style="font-size: 8.5pt; color: #64748B;">Head of Dept / Cell Director</span>
            </td>
            <td class="sig-cell">
              <div class="sig-line"></div>
              <strong>Sanctioned &amp; Sealed By</strong><br/>
              <span style="font-size: 8.5pt; color: #64748B;">Registrar / Controller of Exams</span>
            </td>
          </tr>
        </table>
      </div>

      <div class="footer-note">
        This is an official computer-generated document from Swarrnim ERP. Valid for statutory reporting (NAAC, UGC, AISHE, NIRF).
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff' + htmlDocument], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  const sanitizedTitle = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  link.setAttribute('href', url);
  link.setAttribute('download', `ssiu_report_${sanitizedTitle}_${new Date().toISOString().split('T')[0]}.doc`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
